package gameProject;

import javax.swing.*;
import java.awt.*;

public class StatisticsFrame extends JFrame {
    private Player currentPlayer;

    public StatisticsFrame(Player player) {
        PlayerService ps = new PlayerService();
        Player refreshed = ps.getPlayerById(player.getId());
        this.currentPlayer = (refreshed != null) ? refreshed : player;

        setTitle("Statistik Saya - " + currentPlayer.getUsername());
        setSize(320, 280);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);

        JPanel panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        panel.setBorder(BorderFactory.createEmptyBorder(20, 30, 20, 30));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(6, 5, 6, 5);
        gbc.anchor = GridBagConstraints.WEST;

        JLabel lblTitle = new JLabel("Statistik: " + currentPlayer.getUsername(), SwingConstants.CENTER);
        lblTitle.setFont(new Font("Arial", Font.BOLD, 15));
        gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2; gbc.anchor = GridBagConstraints.CENTER;
        panel.add(lblTitle, gbc);

        gbc.gridwidth = 1;
        gbc.anchor = GridBagConstraints.WEST;

        gbc.gridx = 0; gbc.gridy = 1;
        panel.add(new JLabel("Menang :"), gbc);
        gbc.gridx = 1;
        JLabel lblWins = new JLabel(String.valueOf(currentPlayer.getWins()));
        lblWins.setFont(new Font("Arial", Font.BOLD, 13));
        lblWins.setForeground(new Color(0, 128, 0));
        panel.add(lblWins, gbc);

        gbc.gridx = 0; gbc.gridy = 2;
        panel.add(new JLabel("Kalah  :"), gbc);
        gbc.gridx = 1;
        JLabel lblLosses = new JLabel(String.valueOf(currentPlayer.getLosses()));
        lblLosses.setFont(new Font("Arial", Font.BOLD, 13));
        lblLosses.setForeground(new Color(200, 0, 0));
        panel.add(lblLosses, gbc);

        gbc.gridx = 0; gbc.gridy = 3;
        panel.add(new JLabel("Seri   :"), gbc);
        gbc.gridx = 1;
        JLabel lblDraws = new JLabel(String.valueOf(currentPlayer.getDraws()));
        lblDraws.setFont(new Font("Arial", Font.BOLD, 13));
        lblDraws.setForeground(new Color(150, 100, 0));
        panel.add(lblDraws, gbc);

        int totalGames = currentPlayer.getWins() + currentPlayer.getLosses() + currentPlayer.getDraws();
        gbc.gridx = 0; gbc.gridy = 4;
        panel.add(new JLabel("Total Game:"), gbc);
        gbc.gridx = 1;
        panel.add(new JLabel(String.valueOf(totalGames)), gbc);

        gbc.gridx = 0; gbc.gridy = 5;
        panel.add(new JLabel("Total Skor :"), gbc);
        gbc.gridx = 1;
        JLabel lblScore = new JLabel(String.valueOf(currentPlayer.getScore()));
        lblScore.setFont(new Font("Arial", Font.BOLD, 14));
        lblScore.setForeground(new Color(0, 0, 200));
        panel.add(lblScore, gbc);

        JButton btnClose = new JButton("Tutup");
        gbc.gridx = 0; gbc.gridy = 6; gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.CENTER;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(btnClose, gbc);

        add(panel);

        btnClose.addActionListener(e -> this.dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new StatisticsFrame().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
